<?php
session_start();
error_reporting(0);
if ($_SESSION['level']==""){
   header('location:index2.php');
}
//cek level
if($_SESSION['level']!="admin")
if($_SESSION['level']!="oe")
if($_SESSION['level']!="engineering")
if($_SESSION['level']!="mngeng")
if($_SESSION['level']!="hrgs")
if($_SESSION['level']!="mnghrgs")
if($_SESSION['level']!="ims")
if($_SESSION['level']!="mngims")
if($_SESSION['level']!="logistic")
if($_SESSION['level']!="mnglog")
if($_SESSION['level']!="mtu")
if($_SESSION['level']!="mngmtu")
if($_SESSION['level']!="ppic")
if($_SESSION['level']!="mngppic")
if($_SESSION['level']!="production")
if($_SESSION['level']!="mngprod")
if($_SESSION['level']!="qa")
if($_SESSION['level']!="mngqa")
if($_SESSION['level']!="qc")
if($_SESSION['level']!="mngqc")
if($_SESSION['level']!="admprod")
if($_SESSION['level']!="admeng")
if($_SESSION['level']!="admhrgs")
if($_SESSION['level']!="admims")
if($_SESSION['level']!="admlog")
if($_SESSION['level']!="admmtu")
if($_SESSION['level']!="admppic")
if($_SESSION['level']!="admqa")
if($_SESSION['level']!="admqc")
{
    echo "<script>window.alert(' HAK AKSES DILARANG ANDA AKAN DI LOGOUT OTOMATIS !!!')
          window.location='index.php'</script>";
}
?>